import { useState, useEffect } from "react";
import styles from "@/styles/Information.module.css";
import { Stack, Text } from "@chakra-ui/react";

const ai_image_url = (index: number) => {
  const base_url = "./ai/ai-";
  const indexed_url = `${base_url}${index.toString().padStart(2, "0")}.png`;
  return indexed_url;
};

const AIExamples = () => {
  const color = "white";
  const [currentIndex, setCurrentIndex] = useState(1);
  const [currentImageURL, setCurrentImageURL] = useState(ai_image_url(currentIndex));

  useEffect(() => {
    const interval = setInterval(() => {
      if (currentIndex > 9) {
        setCurrentIndex(1);
        setCurrentImageURL(ai_image_url(currentIndex));
        console.log(currentImageURL);
      } else {
        setCurrentIndex(currentIndex + 1);
        setCurrentImageURL(ai_image_url(currentIndex));
        // console.log(currentImageURL);
      }
    }, 5000); // 5000 milliseconds = 5 seconds

    // Clean up the interval when the component is unmounted
    return () => clearInterval(interval);
  }, [currentIndex]);

  return (
    <>
      <div className={styles.main}>
        <img className={styles.image} src={currentImageURL} alt='' />
        {/* <Text color={color} fontSize='md'>
          {currentImageURL}
        </Text> */}
      </div>
      <div className={styles.side}>
        <Stack spacing={4} color='yellow'>
          <Text color={color} fontSize='4xl' fontWeight='bold'>
            Web3/AI Fusion
          </Text>
          <Text color={color} fontSize='lg'>
            The NFT exhibition is an experiment exploring NFTs as a vehicle for delivering art, consisting of 41
            original pieces by artist Omar Ochoa, and subsequent pieces generated by an AI trained on these originals.
            The AI learns Ochoa&apos;s style and produces unique pieces based on it. This experiment emphasizes the
            empowering potential of AI in enhancing an artist&apos;s creativity. It advocates for an artist-AI
            partnership within the web3 ecosystem, a decentralized platform that strengthens security, transparency, and
            ownership via blockchain. This exhibition fuses artistic skill with advanced technology, highlighting the
            potential of AI-human collaboration rather than viewing AI as a threat to creativity. It invites audiences
            to consider the complex relationship between human artistry, technology, and the transformative capacity of
            web3.
          </Text>
        </Stack>
      </div>
    </>
  );
};

export default AIExamples;
